// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: otp.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "otp.v1";

export interface SendOtpRequest {
  email: string;
}

export interface SendOtpResponse {
}

export interface ValidateOtpRequest {
  email: string;
  hash: string;
  otp: string;
}

export interface ValidateOtpResponse {
  otpValidation: boolean;
}

export const OTP_V1_PACKAGE_NAME = "otp.v1";

export interface OtpServiceClient {
  sendOtp(request: SendOtpRequest): Observable<SendOtpResponse>;

  validateOtp(request: ValidateOtpRequest): Observable<ValidateOtpResponse>;
}

export interface OtpServiceController {
  sendOtp(request: SendOtpRequest): Promise<SendOtpResponse> | Observable<SendOtpResponse> | SendOtpResponse;

  validateOtp(
    request: ValidateOtpRequest,
  ): Promise<ValidateOtpResponse> | Observable<ValidateOtpResponse> | ValidateOtpResponse;
}

export function OtpServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["sendOtp", "validateOtp"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OtpService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OtpService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const OTP_SERVICE_NAME = "OtpService";
